/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InstancesRouteImport } from './routes/instances'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as InstancesInstanceIdRouteImport } from './routes/instances_.$instanceId'
import { Route as MrsInstanceIdGitlabProjectIdIidRouteImport } from './routes/mrs.$instanceId.$gitlabProjectId.$iid'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesRoute = InstancesRouteImport.update({
  id: '/instances',
  path: '/instances',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const InstancesInstanceIdRoute = InstancesInstanceIdRouteImport.update({
  id: '/instances_/$instanceId',
  path: '/instances/$instanceId',
  getParentRoute: () => rootRouteImport,
} as any)
const MrsInstanceIdGitlabProjectIdIidRoute =
  MrsInstanceIdGitlabProjectIdIidRouteImport.update({
    id: '/mrs/$instanceId/$gitlabProjectId/$iid',
    path: '/mrs/$instanceId/$gitlabProjectId/$iid',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/instances': typeof InstancesRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/instances/$instanceId': typeof InstancesInstanceIdRoute
  '/mrs/$instanceId/$gitlabProjectId/$iid': typeof MrsInstanceIdGitlabProjectIdIidRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/instances': typeof InstancesRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/instances/$instanceId': typeof InstancesInstanceIdRoute
  '/mrs/$instanceId/$gitlabProjectId/$iid': typeof MrsInstanceIdGitlabProjectIdIidRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/instances': typeof InstancesRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/instances_/$instanceId': typeof InstancesInstanceIdRoute
  '/mrs/$instanceId/$gitlabProjectId/$iid': typeof MrsInstanceIdGitlabProjectIdIidRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/instances'
    | '/settings'
    | '/skills'
    | '/instances/$instanceId'
    | '/mrs/$instanceId/$gitlabProjectId/$iid'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/instances'
    | '/settings'
    | '/skills'
    | '/instances/$instanceId'
    | '/mrs/$instanceId/$gitlabProjectId/$iid'
  id:
    | '__root__'
    | '/'
    | '/instances'
    | '/settings'
    | '/skills'
    | '/instances_/$instanceId'
    | '/mrs/$instanceId/$gitlabProjectId/$iid'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InstancesRoute: typeof InstancesRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
  InstancesInstanceIdRoute: typeof InstancesInstanceIdRoute
  MrsInstanceIdGitlabProjectIdIidRoute: typeof MrsInstanceIdGitlabProjectIdIidRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instances': {
      id: '/instances'
      path: '/instances'
      fullPath: '/instances'
      preLoaderRoute: typeof InstancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instances_/$instanceId': {
      id: '/instances_/$instanceId'
      path: '/instances/$instanceId'
      fullPath: '/instances/$instanceId'
      preLoaderRoute: typeof InstancesInstanceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mrs/$instanceId/$gitlabProjectId/$iid': {
      id: '/mrs/$instanceId/$gitlabProjectId/$iid'
      path: '/mrs/$instanceId/$gitlabProjectId/$iid'
      fullPath: '/mrs/$instanceId/$gitlabProjectId/$iid'
      preLoaderRoute: typeof MrsInstanceIdGitlabProjectIdIidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InstancesRoute: InstancesRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
  InstancesInstanceIdRoute: InstancesInstanceIdRoute,
  MrsInstanceIdGitlabProjectIdIidRoute: MrsInstanceIdGitlabProjectIdIidRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
